# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4



trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'



- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: SendEmail@1
  inputs:
    To: 'shubham.jain@fiserv.com'
    From: '$(Build.RequestedForEmail)'
    Subject: 'Tech Carnival - $(Agent.JobStatus)'
    Body: |
      <html>
      
      <body>
      <table cellspacing="10" >
      <tr><td><b>Build Definition Name:</b></td><td>$(Build.DefinitionName)</td></tr>
      <tr><td><b>Build ID:</b></td><td>$(Build.BuildNumber)</td></tr>
      <tr><td><b>Build Requested By:</b></td><td>$(Build.RequestedFor)</td></tr>
      <tr><td><b>Status:</b></td><td>$(Agent.JobStatus)</td></tr>
      </table>
      
       </body>
      
       
      
      </html>
    BodyAsHtml: true
    AddAttachment: false
    SmtpServer: 'IWPETPV.corp.checkfree.com'
    SmtpPort: '25'
    UseSSL: false